### ISSUE TITLE
Large Size

### ISSUE THREAD

**Issue by hpdeifel** [flathub/com.github.xournalpp.xournalpp#11]
`xournalpp` currently has a download size of 1.6GB without locale and runtimes. Is this really needed?

```
       ID                                                  Branch               Remote               Download
 1.     com.github.xournalpp.xournalpp                      stable               flathub                < 1,6 GB
 2.     com.github.xournalpp.xournalpp.Locale               stable               flathub              < 185,5 kB (partial)
```

In contrast, `xournal` is 5.9MB

**Comment by muelli** [comment]
well. the number of actually transferred bytes may be significantly lower than 1.6GB. That's why there is the `<`, I guess. It depends on how much you have already downloaded for older versions of this or other apps.

The reason for the size is the (shared) LaTeX extension that was requested in https://github.com/flathub/com.github.xournalpp.xournalpp/issues/7
Once you have downloaded that, either for this or any other app, then it won't be downloaded again.

With 6MB Xournal won't do LaTeX, I suppose.

Note that I don't care much whether LaTeX should be available for the app. It seemed, though, that some users make use of that functionality. At the end of the day, upstream would need to decide whether they want to have this feature shipped.

**Comment by hpdeifel** [comment]
I understand. My concern wasn't actually the download size, but the storage space requirement. Installing `xournalpp` made my admittedly small root partition fill up.

Would it be somehow possible to install latex as an extension separately from the rest of the app? I'm thinking similarly to how GTK themes are handled.

**Comment by muelli** [comment]
that could be cool, yeah. I don't know that works, though and whether Extensions can be used for apps. Maybe @Alexander-Wilms knows..? (sorry for pinging directly, I hope you don't mind).

**Comment by Alexander-Wilms** [comment]
No problem. I haven't been very active maintaining Flatpaks recently, so I'n not sure if an extension needs to use the same reverse-DNS name, like e.g. org.freedesktop.Platform.GStreamer for org.gnome.Platform. See also https://github.com/flatpak/flatpak/wiki/Extensions

If that works, you'd only need to [add the path](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/blob/branch/18.08/org.freedesktop.Sdk.Extension.texlive.yaml#L104) at runtime.

**Comment by muelli** [comment]
I think I've managed to make it work: https://github.com/flathub/com.github.xournalpp.xournalpp/commit/536d96fe318e349025d2eb271c044b546bbb0f0e

@hpdeifel can you try the beta build, once it has successfully built?

@roblem would manually installing the extension work for you?

**Comment by roblem** [comment]
That works as long as there are clear instructions.

**Comment by hpdeifel** [comment]
What do I have to do?

```
flatpak install https://dl.flathub.org/build-repo/11685/com.github.xournalpp.xournalpp.flatpakref
```

still installs 1.6GB

**Comment by muelli** [comment]
right. I see why. I didn't actually stop it from installing texlive into the /app/ directory. The current beta build should be smaller. https://flathub.org/builds/#/builders/32/builds/12293
Can you try again?

**Comment by hpdeifel** [comment]
Not sure if I'm missing something, but I get:

```
➤ flatpak install https://dl.flathub.org/build-repo/11732/com.github.xournalpp.xournalpp.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/11732/com.github.xournalpp.xournalpp.flatpakref: Server returned status 404: Not Found
```

The build page on https://flathub.org/builds/#/builders/32/builds/12293 says that "publish job" failed. Maybe that's the problem?

**Comment by muelli** [comment]
I've pushed the extension.

**Comment by hpdeifel** [comment]
Perfect! Thank you very much for your work!
