### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by Technius** [flathub/com.github.xournalpp.xournalpp#13]
Currently, the manifest uses the file chooser portal, but this is insufficient for documents outside of `xdg-documents` because Xournal++ may also need to load background PDFs. Unfortunately, it seems like the best we can do (without resorting to more involved methods) is to grant host file permissions.

**Comment by TingPing** [comment]
> Currently, the manifest uses the file chooser portal, but this is insufficient for documents outside of xdg-documents

That means its *not* using the portal. And the fix is for the application to use the portal.

**Comment by muelli** [comment]
What do you think are likely locations that need to be accessed?
Should the user's home directory be sufficient?

**Comment by Technius** [comment]
> That means its _not_ using the portal. And the fix is for the application to use the portal.

I was quite vague on the details, so let me give you a concrete example. Suppose I open a PDF file using the file chooser (and by extension, the portal) that I can't access with the default permissions in the manifest (e.g. on a mounted data partition `/media/data-partition/my-files`). Then I create some annotations and save the annotations in the same data partition. Now, I reopen Xournal++ and open the annotation file again. The annotation file will need to load the PDF file but will fail to do so because the PDF file has not been opened with the portal.

To be clear: I'm not actually for adding host file permissions, but all of the alternatives I've thought of will lead to poor UX. And poor UX is going to lead to users granting host permissions with an override.

* Users explicitly granting permissions to _every_ location containing PDFs they want to annotate (i.e. through an override). When they have PDFs all over their computers, this will become annoying very quickly.
* Enumerating locations in the manifest leads to the the same annoyance issues.
* A compromise might be to add readonly host file permissions, but I still don't think that's a very good idea.
* Is there a portal that allows users to receive a prompt when the application attempts to access a file not explicitly allowed (e.g. like Windows UAC)? This is definitely less annoying than the previous options but it can be problematic when the application creates an autosave or when the user loads a document with a lot of external resources (e.g. images).

The fact that PDFs are not coupled with the annotation can be viewed as both a blessing (smaller file sizes) and a curse (this problem, or when the PDF is moved to another location), which is why we (the Xournal++ team) are working on a new "bundled" file format. But there's still several months or at least a year before it will be available in a release.

> What do you think are likely locations that need to be accessed?
> Should the user's home directory be sufficient?

Home directory is insufficient, as shown in my example above.

**Comment by muelli** [comment]
I've set filesystem access to host  :(
