### ISSUE TITLE
Cannot access most directories when opening file

### ISSUE THREAD

**Issue by nicolae-stroncea** [flathub/com.github.xournalpp.xournalpp#14]
- When choosing `File->Open`, I can only access the directory Documents, so I cannot read or write a file anywhere outside of that.
- In the majority of cases I will have my documents in various folders so being able to read and write a file wherever I want on the system would be very useful.

**Comment by Technius** [comment]
If you don't care about Flatpak sandboxing, run this command to enable access to any folder:

```
flatpak override --filesystem=host com.github.xournalpp.xournalpp
```

Related: #13

**Comment by nicolae-stroncea** [comment]
Problem solved, thanks!
