### ISSUE TITLE
Xournalpp missing icon in Software Centre

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.github.xournalpp.xournalpp#2]
![Screenshot from 2019-10-11 15-24-31](https://user-images.githubusercontent.com/33983090/66654837-57b1b380-ec3b-11e9-949b-a447fb0ae3d2.png)

**Comment by Technius** [comment]
Please report this on the [Xournal++ issue tracker](https://github.com/xournalpp/xournalpp/issues).

**Comment by muelli** [comment]
hm. that doesn't sound good. 
There is https://github.com/xournalpp/xournalpp/issues/1442 which indicates problems with Wayland. Are you running Wayland?

**Comment by Eonfge** [comment]
@muelli Nope, X11 here. Keep in mind, it's only the store icon that doesn't work for me.
