### ISSUE TITLE
Fatal error after installing LateX support

### ISSUE THREAD

**Issue by feralber** [flathub/com.github.xournalpp.xournalpp#21]
After update to 1.0.20 Xournal++ fails to start:
```
$ flatpak run com.github.xournalpp.xournalpp 
bwrap: Can't mkdir /app/extensions: Read-only file system
error: ldconfig failed, exit status 256
```
If I uninstall the texlive extension, then it works.

**Comment by muelli** [comment]
ouch.
Can confirm.
Let me revert the commit, then.
Sorry for the breakage.

**Comment by LittleHuba** [comment]
We do not create nor access this path in our code. This looks more like texlive requires this path...

**Comment by muelli** [comment]
The weird thing is that it worked with the previous version of Xournalpp. Since neither the runtime nor the texlive extension have changed, my intuition is that something in the Xournalpp has changed.

But let's bump the runtime version first and check whether it works better, then.

**Comment by muelli** [comment]
I've pushed the new version to beta. Can you give that a try once it has built?

**Comment by LittleHuba** [comment]
This looks related but I honestly have no experience with flatpak: https://github.com/flatpak/flatpak/issues/1341

**Comment by muelli** [comment]
yep, good catch! I think I've got it. Thanks!

**Comment by feralber** [comment]
Thank you! That was fast!
