### ISSUE TITLE
Make Lua plugins available in the flatpak version

### ISSUE THREAD

**Issue by rolandlo** [flathub/com.github.xournalpp.xournalpp#27]
Currently Lua Plugins (and the whole plugin menu) are not included in the flatpak version of Xournal++, because Lua is not available. I have a modified `com.github.xournalpp.xournalpp.yaml` that includes `Lua` and `lua-lgi`. The latter is needed in some plugins for creating a GUI and pretty useful in general.  

Now I am planning to make a pull request. The problem is that `lua-lgi` is currently not compatible with `Gtk 4` (see https://github.com/pavouk/lgi/issues/226) and neither is it compatible with the `org.gnome.Sdk//40` extension (same error). It does work with `org.gnome.Sdk//3.38`.

Now either we downgrade from 40 to 3.38 or we don't include the `lua-lgi`. Having Lua plugin support without `lua-lgi` is still an improvement.

What option would you prefer @muelli?

**Comment by muelli** [comment]
hm. With 3.38 the cursor problem comes back, right? I don't whether having lua outweighs the cursor problem. My feeling says that it's well worth it, but I am not affected by the cursor problem (neither do I use Lua).
Would using gtk3 in GNOME 40 be an option? It'd be quite a hack, I guess, but it may combine the benefits of Lua and the 40 runtime.

**Comment by rolandlo** [comment]
No, the cursor problem won't come back. It would just come back when using the freedesktop runtime instead of the bigger Gnome runtime.
