### ISSUE TITLE
Use TinyTeX instead of huge texlive extension

### ISSUE THREAD

**Issue by rolandlo** [flathub/com.github.xournalpp.xournalpp#64]
Currently when users of the xournalpp flatpak want to use LaTeX they are supposed to install `org.freedesktop.Sdk.Extension.texlive//22.08` which has an insane size of `7.5 GB` in light of the fact, 
that most users just want to display simple formulas. 
For the snap package (where there is no `texlive` extension) we bundle `TinyTeX` with a selection of packages (specified in https://github.com/kenvandine/xournalpp/blob/stable/pkgs-custom.txt) that may be useful for users. See
https://github.com/kenvandine/xournalpp/blob/f16e02baff2f1712683a63ab587c2e90a84db4bb/snapcraft.yaml#L134-L155
For most use cases it is completely sufficient. With `TinyTeX` and these selected packages included, the `xournalpp*.snap` file has a size of roughly `90 MB`, which is by a large factor smaller than the `7.5 GB` that the `texlive` extension for the flatpak pulls in. Even when you had say 20 flatpak packages that need `TinyTeX` (which sounds improbable) it would still be much smaller than the `texlive` extension.

I suggest to bundle `TinyTeX` with the flatpak version as well, ideally in a way that those who want to use the `texlive` extension (because they need the full `texlive`) can still use it.

**Comment by Eonfge** [comment]
> I suggest to bundle TinyTeX with the flatpak version as well, ideally in a way that those who want to use the texlive extension (because they need the full texlive) can still use it.

This would be the hardest part... I don't know how xournalpp can easily switch from the light to the full version.

**Comment by rolandlo** [comment]
Xournal++ uses `g_find_program_in_path` to locate the executable. The [docs](https://docs.gtk.org/glib/func.find_program_in_path.html) say
> Locates the first executable named program in the user’s path, in the same way that execvp() would locate it.

I don't know how `execvp()` locates programs. Maybe it just depends on the order of the different paths in the `PATH` environment variable. So if the path to the light version is at the end, the full version would be used if it is there. Not sure about it.
In any case the `LaTeX generator` generator in Xournal++ can be specified in the preferences. If you use the full absolute path, `g_find_program_in_path` will find the one you want.

**Comment by rolandlo** [comment]
I checked the code of `g_find_program_in_path` in `glib/gutils.c` https://github.com/GNOME/glib/blob/main/glib/gutils.c#L245-L443
On Unix systems, when the path has no empty entry (which stands for the current directory), `g_find_program_in_path` just goes from left to right through the directories, appends the program name and checks if the resulting file is executable.
So yes, Xournal++ (on Linux) will use the LaTeX generator whose directory appears first in the `PATH` environment variable. This means that simply adding the directory of TinyTeX at the end of `PATH` (in https://github.com/flathub/com.github.xournalpp.xournalpp/blob/master/com.github.xournalpp.xournalpp.yaml#L39) will make the Xournal++ flatpak use the `texlive` extension if it is present.

**Comment by Eonfge** [comment]
Sounds good to me.

I must apologise though. I am a little pre-occupied right now so I don't have the time to do this myself. Pull requests are always welcome, but I'll need to prioritise other things first.

@muelli Do you have some time to look into this?

**Comment by muelli** [comment]
there is precendence for tinytex: https://github.com/flathub/net.giuspen.cherrytree/blob/2c52a51db3c9c545ad7950ed46cea0cd020f873e/net.giuspen.cherrytree.json#L243

looks very simple, actually.
maybe don't unpack to /app/bin/ but rather /app/tinytex/ or so, and append that path like suggested.

I have other things on my plate at the moment, so I can't give it a try right now.

**Comment by Eonfge** [comment]
@rolandlo Could you shine your light on this: https://github.com/flathub/com.github.xournalpp.xournalpp/pull/68

Doesn't actually work but I don't know why.

**Comment by rolandlo** [comment]
@Eonfge Thank you for working on this.

From reading the log-file inside `$XDG_RUNTIME_DIR/.flatpak/com.github.xournalpp.xournalpp/tmp/xournalpp-2/tex/` I can see that the `standalone` package is missing:

```term
cat $XDG_RUNTIME_DIR/.flatpak/com.github.xournalpp.xournalpp/tmp/xournalpp-2/tex/tex.log
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex 2022.4.4)  5 DEC 2022 21:57
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**/tmp/xournalpp-2/tex/tex.tex
(/tmp/xournalpp-2/tex/tex.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24>

! LaTeX Error: File `standalone.cls' not found.
```

Next it might complain about the `scontents` package missing. Would it be possible to install packages with `tlmgr` as in https://github.com/kenvandine/xournalpp/blob/88c47f67e0d02f37f2329e4ffc7cc05772c31e99/snapcraft.yaml#L154?

**Comment by muelli** [comment]
> Would it be possible to install packages with `tlmgr` as in https://github.com/kenvandine/xournalpp/blob/88c47f67e0d02f37f2329e4ffc7cc05772c31e99/snapcraft.yaml#L154?

hrm. It probably wants to connect to the internet and download things. That'll be a problem. If it's possible to pre-download things and let tlmgr know about, it might work.

**Comment by rolandlo** [comment]
> > Would it be possible to install packages with `tlmgr` as in https://github.com/kenvandine/xournalpp/blob/88c47f67e0d02f37f2329e4ffc7cc05772c31e99/snapcraft.yaml#L154?
> 
> hrm. It probably wants to connect to the internet and download things. That'll be a problem. If it's possible to pre-download things and let tlmgr know about, it might work.

It works when adding network sharing to the tinytex build (after specifying the build-system):
```yaml
    build-options:
      build-args:
      - --share=network
```

I have also noticed that `tlmgr` needs to be updated before installing packages. This e.g. works:
```
      - /app/tinytex/bin/*/tlmgr update --self
      - /app/tinytex/bin/*/tlmgr install standalone scontents varwidth xargs
```
and 
```
      - /app/tinytex/bin/*/tlmgr update --self
      - /app/tinytex/bin/*/tlmgr install $(cat pkgs-custom.txt | tr '\n' ' ')
```
also works when adding [`pkgs-custom.txt`](https://github.com/kenvandine/xournalpp/blob/stable/pkgs-custom.txt) to the sources.

Only these packages are not contained in the base installation (note that for the snap package a smaller base installation was used) and need to be put into `pkgs-custom.txt`:

```
[1/15, ??:??/??:??] install: adjustbox [14k]
[2/15, 00:06/10:49] install: collectbox [3k]
[3/15, 00:06/08:56] install: currfile [4k]
[4/15, 00:07/08:29] install: filemod [4k]
[5/15, 00:08/08:15] install: fp [19k]
[6/15, 00:09/05:07] install: gincltex [2k]
[7/15, 00:10/05:27] install: grffile [4k]
[8/15, 00:11/05:31] install: listings [143k]
[9/15, 00:12/01:30] install: ms [3k]
[10/15, 00:13/01:36] install: pgf [701k]
[11/15, 00:16/00:25] install: pgfplots [518k]
[12/15, 00:18/00:18] install: scontents [8k]
[13/15, 00:19/00:19] install: standalone [12k]
[14/15, 00:20/00:20] install: varwidth [5k]
[15/15, 00:21/00:21] install: xargs [4k]
```

@Eonfge

**Comment by muelli** [comment]
> It works when adding network sharing to the tinytex build (after specifying the build-system):

it won't for flathub as it's forbidden.

**Comment by rolandlo** [comment]
> > It works when adding network sharing to the tinytex build (after specifying the build-system):
> 
> it won't for flathub as it's forbidden.

Ah, I didn't know about that. I have found a solution that works without accessing the internet during build though. See https://github.com/flathub/com.github.xournalpp.xournalpp/pull/68#pullrequestreview-1207251037

**Comment by Eonfge** [comment]
This works for me! Only not sure if it works when switching between tinytex and the full package.

**Comment by rolandlo** [comment]
> This works for me! Only not sure if it works when switching between tinytex and the full package.

The switching works. I just tested using my custom LaTeX template (which uses multiple packages not available in the small version)  with the full package successfully.

**Comment by Eonfge** [comment]
So, @muelli you agree?

**Comment by muelli** [comment]
you mean with using tinytex? Sure!
