### ISSUE TITLE
Please disable audio by default

### ISSUE THREAD

**Issue by ovari** [flathub/com.github.xournalpp.xournalpp#83]
Please disable audio by default.

> All reports here were specific to the flatpak on Linux Mint.
> 
> If you want that the Xournal++ flatpak opens without disabling audio (on Linux Mint), open an issue on the [flathub repo](https://github.com/flathub/com.github.xournalpp.xournalpp).
Otherwise just run `flatpak run com.github.xournalpp.xournalpp --disable-audio` once and disable audio in the preferences for the future.

https://github.com/xournalpp/xournalpp/issues/5020#issuecomment-1700724561

Thank you

**Comment by Eonfge** [comment]
Sorry for missing your issue. 

As it is, this is something that @rolandlo will have to decide as he's directly involved with Xournal. We have lots of users to think about, and Linux Mint is the only distribution that has this problem... which dates back to an [issue from two years ago](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/352).

So my call is; No. This is a Linux Mint problem and we can't make Xournal worse for everybody, just to help Linux Mint users.

**Comment by ovari** [comment]
> Linux Mint is the only distribution that has this problem... which dates back to an [issue from two years ago](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/352).

@mtwebster @clefebvre Are you aware of this issue? Is there an ETA when this will be fixed in Linux Mint? Thank you

**Comment by mtwebster** [comment]
No idea...  I  see this from  a search: https://github.com/linuxmint/mint21-beta/issues/38 but it appeared resolved. I can't monitor every issue tracker on github. The Mint forums are not for bugs.

I'll have a look when I get a chance.

**Comment by rolandlo** [comment]
I really hope this can be fixed in Mint and agree with @Eonfge that we shouldn't disable audio by default.
